name: Testing

on:
  push:
    paths:
      - .github/workflows/test.yml
    branches: 
      - main

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    
    steps:

      - name: Checkout
        uses: actions/checkout@v3
      
      - name: Set up JDK 17
        uses: actions/setup-java@3
        with:
          java-version: 17
          distribution: 'oracle'
      
      - name: Run tests
        run: ./gradlew test